export type TNotificationType =
  | "NOTIFICATION_FOLLOW_REQUEST"
  | "NOTIFICATION_FOLLOW_ACCEPTED"
  | "NOTIFICATION_FOLLOW_PUBLIC"
  | "NOTIFICATION_UPDATE_LIKED"
  | "NOTIFICATION_UPDATE_COMMENTED"
  | "NOTIFICATION_FOLLOWED_POSTED";
